/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Facade.Fachada;
import Modelo.Actividad;
import Modelo.Estudiante;
import Modelo.Materia;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.runtime.regexp.joni.exception.JOniException;


public class ProfesorCurso extends javax.swing.JFrame {
    DefaultTableModel modeloEstudiante,modeloActividad;
    DefaultComboBoxModel<String> modeloMateria;
    int numFila=0;
    private ArrayList<Materia> listaMateria;
    private ArrayList<Estudiante> listaEstudiante;
    private ArrayList<Actividad> listaActividad;
    private Fachada f;
   
    public ProfesorCurso() {
        f= new Fachada();
        
        listaMateria=f.buscarListaMateriaXProfesor(2);
        String[]materias=new String[listaMateria.size()+1];
        initComponents();
        
        materias[0]="Materia";
        for (int i = 1; i <= listaMateria.size(); i++) {
            materias[i]=listaMateria.get(i-1).getNombre();
            
        }
        
        
         //String[]materias={"Materia","Analisis de algoritmos","Sistemas operativos","Aseguramiento de la calidad de software"};
        
        
        //creo el modelo del cmbMateria y le agrego los datos al modelo
        modeloMateria=new  DefaultComboBoxModel<>(materias);
        //creo el modelo para cada jtable
        modeloEstudiante= new DefaultTableModel();
        modeloActividad= new DefaultTableModel();
        
        //agrego las columnas a cada modelo
        modeloEstudiante.addColumn("Matricula");
        modeloEstudiante.addColumn("Nombre(s)");
        modeloEstudiante.addColumn("Ap Paterno");
        modeloEstudiante.addColumn("Ap Materno");
        
        modeloActividad.addColumn("Actividad");
        modeloActividad.addColumn("Descripcion");
        modeloActividad.addColumn("Fecha de entrega");
        modeloActividad.addColumn("Calificacion");
        
        //agrego el modeloMateria con los datos agregados a  cmbMateria
         cmbMateria.setModel(modeloMateria);

        //agrego cada modelo a su respectivo jtable
        JTListaEstudiante.setModel(modeloEstudiante);
        JTListaActividad.setModel(modeloActividad);
        
        //evito que se puedan mover las columnas de cada jtable
        JTListaEstudiante.getTableHeader().setReorderingAllowed(false);
        JTListaActividad.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSeleccionar = new javax.swing.JLabel();
        cmbMateria = new javax.swing.JComboBox<>();
        lblEstudiante = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTListaEstudiante = new javax.swing.JTable();
        lblActividadeEstudiante = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTListaActividad = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clases");
        setPreferredSize(new java.awt.Dimension(1100, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSeleccionar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSeleccionar.setText("Seleccionar:");
        getContentPane().add(lblSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 80, -1));

        cmbMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 380, 30));

        lblEstudiante.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEstudiante.setText("Estudiante(s):");
        getContentPane().add(lblEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, -1));

        JTListaEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido paterno", "Apellido materno"
            }
        ));
        JTListaEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTListaEstudianteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTListaEstudiante);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 360, 221));

        lblActividadeEstudiante.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblActividadeEstudiante.setText("Actividad(es) Estudiante:");
        getContentPane().add(lblActividadeEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 150, -1));

        JTListaActividad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(JTListaActividad);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 630, 220));

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 360, 110, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        //invoca ventana anterior lisset
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cmbMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMateriaActionPerformed
        String[] alumnos;
        int contador=0;
        
//        int filas;
//        filas=modeloActividad.getRowCount();
//        System.out.println("Actividades: "+filas);
//        filas=modeloEstudiante.getRowCount();
//        System.out.println("Estudiantes: "+filas);
       
        for (int i = 0; i < modeloActividad.getRowCount(); i++) {
                modeloActividad.removeRow(i);
            }
         for (int i = 0; i < modeloEstudiante.getRowCount(); i++) {
                modeloEstudiante.removeRow(i);
            }
        
         
        String materiaSeleccionada=cmbMateria.getSelectedItem().toString();
        
        for (int i = 0; i <listaMateria.size(); i++) {
            if(materiaSeleccionada.equals(listaMateria.get(i).getNombre())){
                listaEstudiante=f.buscarListaAlumnoXMateria(listaMateria.get(i).getId());
                for (int j = 0; j < listaEstudiante.size(); j++) {
                     alumnos=new String[4];
                     alumnos[0]=listaEstudiante.get(j).getMatricula();
                     alumnos[1]=listaEstudiante.get(j).getNombre();
                     alumnos[2]=listaEstudiante.get(j).getAp_paterno();
                     alumnos[3]=listaEstudiante.get(j).getAp_materno();
                     modeloEstudiante.addRow(alumnos);
                }
                
            }
        }
        
        
       

        
        
    }//GEN-LAST:event_cmbMateriaActionPerformed

    private void JTListaEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTListaEstudianteMouseClicked
    
        String[] actividades;
        //obtengo la fila seleccionada del JTListaEstudiante
        int filaSeleccionada=JTListaEstudiante.getSelectedRow();
        if(filaSeleccionada>=0){
            
            for (int i = 0; i < modeloActividad.getRowCount(); i++) {
                    modeloActividad.removeRow(i);
            }
            
            
            String matricula=JTListaEstudiante.getValueAt(filaSeleccionada, 0).toString();

            for (int i = 0; i <listaEstudiante.size(); i++) {
                 if(matricula.equals(listaEstudiante.get(i).getMatricula())){
                    listaActividad=f.buscarListaActividadXAlumno(matricula);
                     for (int j = 0; j <listaActividad.size(); j++) {
                         actividades=new String[4];
                         actividades[0]=listaActividad.get(j).getNombre();
                         actividades[1]=listaActividad.get(j).getDescripcion();
                         actividades[2]=listaActividad.get(j).getFecha_entrega();
                         actividades[3]=listaActividad.get(j).getCalificacion();
                         modeloActividad.addRow(actividades);
                     }
                 }
            }
        }
        
        System.out.println("Selecionaste una fila");
    }//GEN-LAST:event_JTListaEstudianteMouseClicked

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfesorCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfesorCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfesorCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfesorCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfesorCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTListaActividad;
    private javax.swing.JTable JTListaEstudiante;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbMateria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblActividadeEstudiante;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JLabel lblSeleccionar;
    // End of variables declaration//GEN-END:variables
}
