/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Examen;
import Modelo.Pregunta;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author tranc
 */
public class ProfesorPreguntasExamen extends javax.swing.JFrame {
    private int numPregunta;
    private int numRespuesta;
    private Examen ex;
    
    public ProfesorPreguntasExamen(int numPregunta,int numRespuesta) {
        this.numPregunta=numPregunta;
        this.numRespuesta=numRespuesta;
        System.out.println("Preguntas: "+numPregunta+"\nRespuestas: "+numRespuesta);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIngresa = new javax.swing.JLabel();
        btnAgregarPregunta = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnCrearExamen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Creando preguntas y respuestas");
        setPreferredSize(new java.awt.Dimension(560, 200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIngresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIngresa.setText("Ingresa:");
        lblIngresa.setPreferredSize(new java.awt.Dimension(40, 14));
        getContentPane().add(lblIngresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, -1));

        btnAgregarPregunta.setText("Agregar Pregunta Con Respuesta");
        btnAgregarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPreguntaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, 50));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 140, 50));

        btnCrearExamen.setText("Crear Examén");
        btnCrearExamen.setEnabled(false);
        btnCrearExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearExamenActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 120, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPreguntaActionPerformed
        ex=new Examen();
        Pregunta p;
        String pregunta,respuesta;
        
        for(int i=0;i<numPregunta;i++){
            p= new Pregunta();
            pregunta= JOptionPane.showInputDialog(null,"Ingresa pregunta "+(i+1));
            while(pregunta.equals("")){
                pregunta= JOptionPane.showInputDialog(null,"Ingresa pregunta "+(i+1));
            }
            p.setNombre(pregunta);
            System.out.println("Pregunta: "+pregunta);
            
            for (int j = 0; j < numRespuesta; j++) {
                respuesta= JOptionPane.showInputDialog(null,"Ingresa respuesta "+(j+1));
                while(respuesta.equals("")){
                    respuesta= JOptionPane.showInputDialog(null,"Ingresa respuesta "+(j+1));
                }   
                
                p.agregarRespuesta(respuesta);
                System.out.println("Respuesta: "+respuesta);
            }
            ex.agregarPregunta(p);
            
        }
        
        btnAgregarPregunta.setEnabled(false);
        btnCrearExamen.setEnabled(true);
        
    }//GEN-LAST:event_btnAgregarPreguntaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
       ProfesorDimensionExamen ventana= new ProfesorDimensionExamen();
       ventana.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCrearExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearExamenActionPerformed
        int confirmar=JOptionPane.showConfirmDialog(null,"¿Confirmar?");
        System.out.println("Confirmar = "+confirmar);
        if(JOptionPane.OK_OPTION == confirmar){
            ProfesorExamen e= new ProfesorExamen(ex);
            e.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnCrearExamenActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ProfesorPreguntasExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ProfesorPreguntasExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ProfesorPreguntasExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ProfesorPreguntasExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ProfesorPreguntasExamen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPregunta;
    private javax.swing.JButton btnCrearExamen;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblIngresa;
    // End of variables declaration//GEN-END:variables
}
